import type { Hero } from './hero.model';

export const EXAMPLE_HEROES: Hero[] = [
  {
    id: '1',
    name: 'Silverwing',
    alias: 'SWing',
    powerClass: 'Aerial',
    power: 92,
    status: 'Active',
    clearanceTier: 'Tier1',
    missionsRun: 47,
    successRate: 0.96,
    threatsFaced: 23,
    bio: 'Master of wind manipulation and aerial combat. Fastest response time on record.',
  },
  {
    id: '2',
    name: 'Dr. Ion',
    alias: 'Spark',
    powerClass: 'Energy',
    power: 88,
    status: 'Active',
    clearanceTier: 'Tier1',
    missionsRun: 34,
    successRate: 0.94,
    threatsFaced: 18,
    bio: 'Quantum electrodynamics expert. Can ionize matter and control electrical fields.',
  },
  {
    id: '3',
    name: 'Vantablack',
    alias: 'Shadow',
    powerClass: 'Mutant',
    power: 75,
    status: 'Active',
    clearanceTier: 'Tier2',
    missionsRun: 52,
    successRate: 0.92,
    threatsFaced: 31,
    bio: 'Absorbs light and electromagnetic radiation. Exceptional stealth operative.',
  },
  {
    id: '4',
    name: 'Aurora Vale',
    alias: 'Aurora',
    powerClass: 'Cosmic',
    power: 85,
    status: 'Injured',
    clearanceTier: 'Tier1',
    missionsRun: 28,
    successRate: 0.89,
    threatsFaced: 14,
    bio: 'Stellar energy channeling. Currently recovering from Titan Incident.',
  },
  {
    id: '5',
    name: 'Magnetar',
    alias: 'Magnet',
    powerClass: 'Energy',
    power: 86,
    status: 'Active',
    clearanceTier: 'Tier1',
    missionsRun: 41,
    successRate: 0.95,
    threatsFaced: 22,
    bio: 'Generates and controls magnetic fields. Critical for infrastructure protection.',
  },
  {
    id: '6',
    name: 'The Tinkerer',
    alias: 'Tech',
    powerClass: 'Tech',
    power: 72,
    status: 'Reserve',
    clearanceTier: 'Tier2',
    missionsRun: 38,
    successRate: 0.91,
    threatsFaced: 19,
    bio: 'Advanced tech integration and hacking. On sabbatical for equipment overhaul.',
  },
  {
    id: '7',
    name: 'Halcyon',
    alias: 'Peace',
    powerClass: 'Psionic',
    power: 79,
    status: 'Active',
    clearanceTier: 'Tier2',
    missionsRun: 31,
    successRate: 0.88,
    threatsFaced: 16,
    bio: 'Telepathy and mental shielding. Specializes in de-escalation ops.',
  },
  {
    id: '8',
    name: 'Rift',
    alias: 'Void',
    powerClass: 'Cosmic',
    power: 89,
    status: 'Active',
    clearanceTier: 'Tier1',
    missionsRun: 24,
    successRate: 0.96,
    threatsFaced: 12,
    bio: 'Spatial distortion and portal creation. Most powerful in dimensional conflicts.',
  },
  {
    id: '9',
    name: 'Ember Cho',
    alias: 'Flame',
    powerClass: 'Energy',
    power: 81,
    status: 'Active',
    clearanceTier: 'Tier2',
    missionsRun: 45,
    successRate: 0.90,
    threatsFaced: 27,
    bio: 'Pyrogenic control. Excellent team synergy with cold-based operatives.',
  },
  {
    id: '10',
    name: 'Null',
    alias: 'Void',
    powerClass: 'Psionic',
    power: 77,
    status: 'MIA',
    clearanceTier: 'Tier2',
    missionsRun: 22,
    successRate: 0.87,
    threatsFaced: 11,
    bio: 'Psychic dampening. Last contact: 18 months ago on Sector 7 assignment.',
  },
  {
    id: '11',
    name: 'Grond',
    alias: 'Stone',
    powerClass: 'Mutant',
    power: 94,
    status: 'Active',
    clearanceTier: 'Tier1',
    missionsRun: 36,
    successRate: 0.93,
    threatsFaced: 20,
    bio: 'Geological manipulation and superhuman durability. Field tank and anchor.',
  },
  {
    id: '12',
    name: 'Ms. Meridian',
    alias: 'Compass',
    powerClass: 'Tech',
    power: 68,
    status: 'Active',
    clearanceTier: 'Tier3',
    missionsRun: 29,
    successRate: 0.85,
    threatsFaced: 15,
    bio: 'Navigation and electromagnetic sensitivity. Invaluable for search and rescue.',
  },
];
